site_name: Organization README Files
site_url: https://readme-hub-test.github.io/organization-readme-pages/

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Organization Repositories:
      - Home: index.md
  - Additional Markdown Files:
