name: Deploy MkDocs GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material requests jq

      - name: Fetch all repositories in the organization
        run: |
          ORGANIZATION="readme-hub-test" 
          REPOS_URL="https://api.github.com/orgs/$ORGANIZATION/repos?per_page=100"
          REPOS=$(curl -s $REPOS_URL | jq -r '.[].name')

          # Create docs/readmes directory and index.md
          mkdir -p docs/readmes

          # Start creating the index.md file
          echo "# Organization Repositories" > docs/index.md
          echo "Here are the README files from all the repositories in the organization:" >> docs/index.md
          echo "" >> docs/index.md

          # Loop through the repositories and fetch their README files
          for REPO in $REPOS; do
            README_URL="https://raw.githubusercontent.com/$ORGANIZATION/$REPO/main/README.md"
            echo "## $REPO" >> docs/index.md
            curl -s $README_URL >> docs/index.md
            echo "" >> docs/index.md
          done

      - name: Build the MkDocs site
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean: true
